---

- name: Provision Web Servers
  hosts: webservers
  tasks:

    - name: Install pip3
      apt:
        update_cache: yes
        name: python3-pip
      become: yes

    - name: Install Docker
      apt:
        name: docker.io
      become: yes

    - name: Start Docker
      shell: |
          systemctl start docker
          systemctl enable docker
      become: true
